server:
  port: 8080

spring:
  application:
    name: balance-api

  datasource:
    url: jdbc:h2:mem:balance-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:29092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
#        spring.json.trusted.packages: "*"
        spring.json.type.mapping: DepositMessage:com.zad.exchangeapi.dto.kafka.DepositMessage,WithdrawMessage:com.zad.exchangeapi.dto.kafka.WithdrawMessage
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      platform: h2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
    enabled: true


external:
  api:
    url: https://v6.exchangerate-api.com/v6
    apiKey: 8ebf845d4d505e16d95c3487



app:
  kafka:
    topics:
      transaction: transaction-queue
      dlq: dlq-topic
      partitions: 3
      replicas: 1
    retries:
      delay: 2000